# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "image-optimizer"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Koz\u{e1}k"]
  s.date = "2012-01-22"
  s.email = "martinkozak@martinkozak.net"
  s.executables = ["image-optimizer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/image-optimizer",
    "image-optimizer.gemspec",
    "lib/image-optimizer.rb"
  ]
  s.homepage = "http://github.com/martinkozak/image-optimizer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Optimizes given JPEG and PNG images or images in given folder."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yaop>, [">= 0"])
      s.add_runtime_dependency(%q<jpegtran>, [">= 0"])
      s.add_runtime_dependency(%q<optipng>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<jpegoptim>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<unix-whereis>, [">= 0"])
      s.add_runtime_dependency(%q<options-hash>, [">= 0"])
      s.add_runtime_dependency(%q<command-builder>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_development_dependency(%q<jeweler2>, [">= 2.0.0"])
    else
      s.add_dependency(%q<yaop>, [">= 0"])
      s.add_dependency(%q<jpegtran>, [">= 0"])
      s.add_dependency(%q<optipng>, [">= 0.2.0"])
      s.add_dependency(%q<jpegoptim>, [">= 0.2.0"])
      s.add_dependency(%q<unix-whereis>, [">= 0"])
      s.add_dependency(%q<options-hash>, [">= 0"])
      s.add_dependency(%q<command-builder>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<yaop>, [">= 0"])
    s.add_dependency(%q<jpegtran>, [">= 0"])
    s.add_dependency(%q<optipng>, [">= 0.2.0"])
    s.add_dependency(%q<jpegoptim>, [">= 0.2.0"])
    s.add_dependency(%q<unix-whereis>, [">= 0"])
    s.add_dependency(%q<options-hash>, [">= 0"])
    s.add_dependency(%q<command-builder>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.14"])
    s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
  end
end

