# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{image-optimizer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Martin Kozák}]
  s.date = %q{2011-05-29}
  s.email = %q{martinkozak@martinkozak.net}
  s.executables = [%q{image-optimizer}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/image-optimizer",
    "image-optimizer.gemspec",
    "lib/image-optimizer.rb"
  ]
  s.homepage = %q{http://github.com/martinkozak/image-optimizer}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.4}
  s.summary = %q{optimizes given JPEG and PNG images or images in given folder.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yaop>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<jpegtran>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<optipng>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<jpegoptim>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<mini_magick>, [">= 3.2.1"])
      s.add_runtime_dependency(%q<unix-whereis>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<options-hash>, [">= 0.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.14"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<yaop>, [">= 0.1.0"])
      s.add_dependency(%q<jpegtran>, [">= 0.1.0"])
      s.add_dependency(%q<optipng>, [">= 0.2.0"])
      s.add_dependency(%q<jpegoptim>, [">= 0.2.0"])
      s.add_dependency(%q<mini_magick>, [">= 3.2.1"])
      s.add_dependency(%q<unix-whereis>, [">= 0.1.0"])
      s.add_dependency(%q<options-hash>, [">= 0.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.14"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<yaop>, [">= 0.1.0"])
    s.add_dependency(%q<jpegtran>, [">= 0.1.0"])
    s.add_dependency(%q<optipng>, [">= 0.2.0"])
    s.add_dependency(%q<jpegoptim>, [">= 0.2.0"])
    s.add_dependency(%q<mini_magick>, [">= 3.2.1"])
    s.add_dependency(%q<unix-whereis>, [">= 0.1.0"])
    s.add_dependency(%q<options-hash>, [">= 0.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.14"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
  end
end

