# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "image-optimizer"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Koz\u{e1}k"]
  s.date = "2012-08-05"
  s.email = "martinkozak@martinkozak.net"
  s.executables = ["image-optimizer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/image-optimizer",
    "image-optimizer.gemspec",
    "lib/image-optimizer.rb",
    "lib/image-optimizer/jpeg.rb",
    "lib/image-optimizer/png.rb",
    "lib/image-optimizer/png.script"
  ]
  s.homepage = "http://github.com/martinkozak/image-optimizer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Optimizes given JPEG and PNG images or images in given folder. Uses several encoders for achieving the best possible lossless compression ratio and tries to employ the most advanced methods such as JPEG algorithmic encoding if available or PNG transparent pixels stripping and automatic color reduction."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yaop>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<which>, [">= 0"])
      s.add_runtime_dependency(%q<hash-utils>, [">= 2.0.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_development_dependency(%q<jeweler2>, [">= 2.0.0"])
    else
      s.add_dependency(%q<yaop>, [">= 0.2.0"])
      s.add_dependency(%q<which>, [">= 0"])
      s.add_dependency(%q<hash-utils>, [">= 2.0.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<yaop>, [">= 0.2.0"])
    s.add_dependency(%q<which>, [">= 0"])
    s.add_dependency(%q<hash-utils>, [">= 2.0.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.14"])
    s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
  end
end

